#!/bin/bash

if xrandr | grep "HDMI-A-0 connected"; then
  # External monitor is active, disable laptop monitor
  xrandr --output HDMI-A-0 --mode 1920x1080 --rate 144
  xrandr --output eDP --off
else
  # Try to activate external monitor
  #xrandr --output eDP --auto
  xrandr --output eDP --mode 2560x1440 --rate 120 --left-of HDMI-A-0
fi
