#!/bin/bash


current=$(brightnessctl g)

case "$1" in
  up)

    new=$((current + 4500))

    if [ "$new" -gt 62451 ]; then
      new=62451
    fi

    brightnessctl s $new
    ;;
  down)

    new=$((current - 4500))

    if [ "$new" -lt 0 ]; then
      new=0
    fi

    brightnessctl s $new
    ;;
  *)
    echo "Usage: $0 {up|down}"
    exit 1
    ;;
esac

