#!/bin/bash


result=$(yad --title="Power" \
  --button="Shutdown:0" \
  --button="Restart:1" \
  --button="Cancel:2" \
  2>/dev/null)

exit_code=$?
#notify-send "$result $exit_code"

if [[ $exit_code -eq 0 ]]; then
  shutdown now
fi

if [[ $exit_code -eq 1 ]]; then
  reboot
fi

exit 0

