#!/bin/bash

if xrandr | grep "HDMI-A-0 connected"; then
  # External monitor is active, disable laptop monitor
  xrandr --output HDMI-A-0 --mode 1920x1080 --rate 144
  xrandr --output eDP --off
  echo "Xft.dpi: 96" | xrdb -merge
else
  # Try to activate external monitor
  #xrandr --output eDP --auto
  xrandr --output eDP --auto
  echo "Xft.dpi: 144" | xrdb -merge
fi
